# -*- coding: utf-8 -*-
"""Kidstories.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkUIs6ImAAwBkcZHbykNTXgnPZR_LiaH
"""

import requests
import re
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

page = requests.get('https://www.ebay.com/sch/i.html?_from=R40&_nkw=Childrens+books&_sacat=0&_ipg=200')
print(page.status_code)

Titles = []
print(page.content)
soup = BeautifulSoup(page.content, 'html.parser')
#soup.find_all('h3', class_ = 's-item__title')
for h3_tag in soup.find_all('h3', class_ = 's-item__title'):
    Title = h3_tag.text
    print(Title)

#Titles.append(Title)
#print(Titles)
#Title.iloc[0:10,0:10]

from google.colab import files
Uploaded =  files.upload()

KS_titles = pd.read_csv('Kidstories.csv' , engine='python')
print (KS_titles)

KS_titles.head()

KST = KS_titles.Title
KST.head()

from google.colab import files
uploaded = files.upload()

EBT= open('EBT.txt', 'w')
EBT.write(Title)

print(Title)

EBT = open(r"EBT.txt", "r").read()
#Search = Childrens book
if re.search (r'^Childrens book?', EBT):
    print('Match found')
else:
    print ('match not found')

for line in re.findall("Childrens book.*", EBT):
    print(line)
    rules = [
    Rule(LinkExtractor(allow=r'questions\?page=[0-9]&sort=newest'),
         callback='parse_item', follow=False)